hivemq/hivemq-extension-sdk

src/main/java/com/hivemq/extension/sdk/api/auth/parameter/ModifiableClientSettings.java

**Motivation**
add the possibility to configure an individual queue limit for each client

add max queue size as a client setting

---

gradle.properties

**Changes**
dependency updates

updated dependencies

---

README.adoc

**Motivation**
Added maven central badge to readme
**Changes**

Added badges to readme

---

build.gradle.kts

build > javadoc search fix for jdk 11

---

README.adoc

Added javadoc badge

---

README.adoc
gradle.properties

**Motivation**
Release version 4.4.1.
**Changes**
Update version to 4.4.1.

Version up to 4.4.1.

---

gradle.properties

version-to-4.4.2-SNAPSHOT

---

gradle.properties

rollback metric dependency update

---

gradle.properties

**Motivation**
Start next development iteration.
**Changes**
Bump version to 4.5.0-SNAPSHOT.

Next development iteration (4.5.0-SNAPSHOT)

---

README.adoc
gradle.properties

Update version to 4.5.0

---

gradle.properties

**Motivation**
Resolves #<issue>
**Changes**

version to 4.6.0-SNAPSHOT

---

build.gradle.kts
gradle.properties

[4.4] Build updates

---

build.gradle.kts
gradle.properties

[4.5] Build updates

---

build.gradle.kts
gradle.properties

[4.6] Build updates

---

.github/workflows/publish.yml
build.gradle.kts
gradle.properties
settings.gradle.kts

* adapted build.gradle.kts for direct maven central publish
* added GitHub action that performs the upload automatically upon release creation

[CI CD] added direct maven central publish

---

.github/workflows/publish.yml
build.gradle.kts
settings.gradle.kts

[4.4] Build improvements

---

.github/workflows/publish.yml
build.gradle.kts
settings.gradle.kts

[4.5] Build improvements

---

.github/workflows/publish.yml
build.gradle.kts
settings.gradle.kts

[4.6] Build improvements

---

build.gradle.kts
gradle.properties
settings.gradle.kts

[4.4] build > update gradle plugins

---

build.gradle.kts
gradle.properties
settings.gradle.kts

[4.5] build > update gradle plugins

---

build.gradle.kts
gradle.properties
settings.gradle.kts

[4.7] build > update gradle plugins

---

CompositeJenkinsfile

**Motivation**
Resolves #<issue>
**Changes**

[4.5] Create composite ci

---

CompositeJenkinsfile

**Motivation**
Resolves #<issue>
**Changes**

[4.4] Create composite ci

---

gradle.properties

[4.7] Update dependencies

---

gradle.properties

**Motivation**
Update dependencies to current versions
**Changes**

[4.7] Dependency updates

---

gradle.properties

**Motivation**
Update dependencies to current versions
**Changes**

[4.6] Dependency updates

---

gradle.properties

**Motivation**
Update dependencies to current versions
**Changes**

[4.5] Dependency updates

---

src/main/java/com/hivemq/extension/sdk/api/async/AsyncOutput.java
src/main/java/com/hivemq/extension/sdk/api/async/SimpleAsyncOutput.java
src/main/java/com/hivemq/extension/sdk/api/auth/parameter/EnhancedAuthOutput.java
src/main/java/com/hivemq/extension/sdk/api/auth/parameter/SimpleAuthOutput.java
src/main/java/com/hivemq/extension/sdk/api/client/parameter/ServerInformation.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/connack/ConnackOutboundInterceptorProvider.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/connect/ConnectInboundInterceptorProvider.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/publish/parameter/PublishInboundOutput.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/AuthenticatorProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/AuthorizerProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/EnhancedAuthenticatorProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/publish/PublishService.java

**Motivation**
https://hivemq.kanbanize.com/ctrl_board/4/cards/6840/details/
**Changes**

[4.8] fix javadoc warnings

---

src/main/java/com/hivemq/extension/sdk/api/async/AsyncOutput.java
src/main/java/com/hivemq/extension/sdk/api/async/SimpleAsyncOutput.java
src/main/java/com/hivemq/extension/sdk/api/auth/parameter/EnhancedAuthOutput.java
src/main/java/com/hivemq/extension/sdk/api/auth/parameter/SimpleAuthOutput.java
src/main/java/com/hivemq/extension/sdk/api/client/parameter/ServerInformation.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/connack/ConnackOutboundInterceptorProvider.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/connect/ConnectInboundInterceptorProvider.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/publish/parameter/PublishInboundOutput.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/AuthenticatorProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/AuthorizerProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/EnhancedAuthenticatorProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/publish/PublishService.java

**Motivation**
https://hivemq.kanbanize.com/ctrl_board/4/cards/6840/details/
**Changes**

[4.7] fix javadoc warnings

---

src/main/java/com/hivemq/extension/sdk/api/async/AsyncOutput.java
src/main/java/com/hivemq/extension/sdk/api/async/SimpleAsyncOutput.java
src/main/java/com/hivemq/extension/sdk/api/auth/parameter/EnhancedAuthOutput.java
src/main/java/com/hivemq/extension/sdk/api/auth/parameter/SimpleAuthOutput.java
src/main/java/com/hivemq/extension/sdk/api/client/parameter/ServerInformation.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/connack/ConnackOutboundInterceptorProvider.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/connect/ConnectInboundInterceptorProvider.java
src/main/java/com/hivemq/extension/sdk/api/interceptor/publish/parameter/PublishInboundOutput.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/AuthenticatorProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/AuthorizerProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/auth/provider/EnhancedAuthenticatorProvider.java
src/main/java/com/hivemq/extension/sdk/api/services/publish/PublishService.java

**Motivation**
https://hivemq.kanbanize.com/ctrl_board/4/cards/6840/details/
**Changes**

[4.5] fix javadoc warnings

---

src/main/java/com/hivemq/extension/sdk/api/services/admin/LicenseEdition.java

**Motivation**
**Changes**
https://hivemq.kanbanize.com/ctrl_board/4/cards/10055/details/

[4.10] update license editions 

---

build.gradle.kts
gradle.properties
gradle/libs.versions.toml

https://hivemq.kanbanize.com/ctrl_board/41/cards/15788/details/
**Motivation**
Resolves #<issue>
**Changes**

Remove dependency to hivemq-platform

---

.github/workflows/publish.yml
build.gradle.kts

**Motivation**
Resolves #30163
**Changes**
JDK 17 is our new baseline.

Upgrade compile target to JDK 17

---

.github/workflows/publish.yml
build.gradle.kts

Reverts hivemq/hivemq-extension-sdk#186

Revert "Upgrade compile target to JDK 17"

---

renovate.json5

https://hivemq.kanbanize.com/ctrl_board/22/cards/35312/details/

Update Renovate configuration
